# -*- coding: utf-8 -*-
"""202507_input.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zu64RIxG6CP_FXsXdXXENtPXZG4ZiCgI
"""

input()

a = input('첫번재 문자열 입력')
b = input('두번재 문자열 입력')

print(a)
print(b)

a+b

a='100'

a + 1

# print 와 input 기능 정리하기
# 사용법
# print( 출력을 원하는 문자열이나 값 또는 수식, 변수 )  -->  출력
# input(적당한 안내문)
# 변수 = input()  --> 사용자가 입력한 값을 변수에 저장

# 사용자로부터 이름을 입력받아서
name = input("이름을 입력하세요-->")
# 다음 형식으로 출력을 한다.
# eX) 안녕하세요 홍길동님 반갑습니다
result = "안녕하세요" +  name + "님 반갑습니다"
print( result  )

# 변수
# 변수명 = 값(숫자, 소수점, 문자열, bool),변수,수식
# 100을 변수에 넣어보기
number = 100

# 문자형 저장하고 출력
name = '홍길동'
print(name)

a = '10'
b = 10
print( int(a) + b)  # int(a) --> 문자열값을 가지는 변수a를 숫자로 변경하는 명령어
print( a + str(b))  # str(b) 숫자를 문자로 변경하는 명령어

# 사용자로부터 값을 3개 입력받아서   input, int
number1 = input()
number2 = input()
number3 = input()

# 입력한 값의 합을 출력  print
print( int(number1)  + int(number2) + int(number3))

# 사용자로부터 값을 3개 입력받아서   input, int
number1 = int(input())
number2 = int(input())
number3 = int(input())

# 입력한 값의 합을 출력  print
print( number1  + number2 + number3)

#  실수를 변수 a에 입력하고   10.50
a = 10.50
#  정수를 변수 b에 입력해서    100
b = 100
# 두 변수를 더한값을 변수 c에 저장하고
c = a + b
# 변수 c를 출력
print(c)

# bool
a = True
b = False
print(a)

# 숫자(int), 실수(float), 문자열(str), 불(bool)  --> type 이라고 함
# 변수에 들어 있는 데이터가 어떤 type인지 확인하는 명령어는 type()

a = 10     # int
b = 10.5   # float
c = '숫자'  # str
d = True  # bool
print(type(a))

# 정리
# print, input, 변수만들고 사용, 다양한 타입, 타입확인, 변수의 데이터 타입을 변환하는 방법

