# -*- coding: utf-8 -*-
"""20250726_summary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QWoX_O0OC0L7xO-sV2uyi49uPQtMkKP_

```
input
print
변수만들기(정수,실수,문자열, bool)
  변수명 = 값
변수 타입 변경하기
  int() float() str() bool()
타입확인하기
  type()
```
"""

# input사용해 보기
# 국어 엉어 수학 점수를 정수로 받아서 총점과 평균을 각각 적당한 변수에 저장하고 출력
# kor, eng, ma
# total, avg

kor = int(input('국어점수 : '))  # 90
eng = int(input('영어점수 : ')) # 95
ma = int(input('수학점수 : '))  # 98
SIZE = 3
# kor = int(kor)
# eng = int(eng)
# ma = int(ma)
total = kor + eng + ma
avg = total / SIZE
print('총점 : ', total)
print('평균 : ', round(avg,2) )

#  관리비 고지서 출력하는 프로그램
#  출력양식

# dong, ho, month, price  -> input으로 입력받아서
#  000동 000호 00월 관리비는 000 입니다.  --> 이런형태로 출력

price = 2500000000000  # 25,000
f"{price:,.0f}"

